from . import website
from . import res_partner
from . import res_config_settings
from . import shrimp_certificate
from . import shrimp_user_certificate_line
from . import shrimp_taste_criterion
from . import shrimp_verification_line
from . import shrimp_verifier_review
from . import shrimp_verification
from . import shrimp_transaction
from . import shrimp_product
from . import shrimp_verification_acceptance
