from . import shrimp_uuid_mixin
from . import res_partner
from . import shrimp_partner_role
from . import res_users
from . import ir_rule
from . import shrimp_certificate
from . import shrimp_user_certificate_line
from . import shrimp_rate_limit
from . import ir_http
