from . import test_tecnico_acceso
from . import test_seguridad_verificacion
from . import test_coherencia_verificacion
from . import test_deshacer_aceptacion
from . import test_multiperfil_verificacion
from . import test_trazabilidad_planta
from . import test_verificacion_declarada
from . import test_ajustes_verificacion
from . import test_filter_drawer_verificacion
